//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class ListPrincipals
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private ListPrincipals() : base("LightSwitchApplication:ListPrincipals")
        {
            global::LightSwitchApplication.ListPrincipals.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static ListPrincipals CreateInstance()
        {
            return new global::LightSwitchApplication.ListPrincipals(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ListPrincipals_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ListPrincipals_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ListPrincipals_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ListPrincipals_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ListPrincipals_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ListPrincipals_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ListPrincipals_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Principals_SelectionChanged();

        partial void Principals_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Principals_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Principals visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Principal> Principals
        {
            get
            {
                return global::LightSwitchApplication.ListPrincipals.DetailsClass.GetValue(this, global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties.Principals);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Principals_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass, global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySet, global::LightSwitchApplication.ListPrincipals.DetailsClass.CommandSet, global::LightSwitchApplication.ListPrincipals.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties.Principals;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass>.Entry
                __ListPrincipalsEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass>.Entry(
                    global::LightSwitchApplication.ListPrincipals.DetailsClass.__ListPrincipals_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.ListPrincipals.DetailsClass.__ListPrincipals_InvokeSavingEvent,
                    global::LightSwitchApplication.ListPrincipals.DetailsClass.__ListPrincipals_InvokeSavedEvent,
                    global::LightSwitchApplication.ListPrincipals.DetailsClass.__ListPrincipals_InvokeClosingEvent,
                    global::LightSwitchApplication.ListPrincipals.DetailsClass.__ListPrincipals_InvokeCreated,
                    global::LightSwitchApplication.ListPrincipals.DetailsClass.__ListPrincipals_InvokeActivated,
                    global::LightSwitchApplication.ListPrincipals.DetailsClass.__ListPrincipals_InvokeSaveErrorEvent);
            private static void __ListPrincipals_InvokeInitializeDataWorkspace(global::LightSwitchApplication.ListPrincipals s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.ListPrincipals_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __ListPrincipals_InvokeSavingEvent(global::LightSwitchApplication.ListPrincipals s)
            {
                bool handled = false;
                s.ListPrincipals_Saving(ref handled);
                return handled;
            }
            private static void __ListPrincipals_InvokeSavedEvent(global::LightSwitchApplication.ListPrincipals s)
            {
                s.ListPrincipals_Saved();
            }
            private static bool __ListPrincipals_InvokeClosingEvent(global::LightSwitchApplication.ListPrincipals s)
            {
                bool cancel = false;
                s.ListPrincipals_Closing(ref cancel);
                return cancel;
            }
            private static void __ListPrincipals_InvokeCreated(global::LightSwitchApplication.ListPrincipals s)
            {
                s.ListPrincipals_Created();
            }
            private static void __ListPrincipals_InvokeActivated(global::LightSwitchApplication.ListPrincipals s)
            {
                s.ListPrincipals_Activated();
            }
            private static bool __ListPrincipals_InvokeSaveErrorEvent(global::LightSwitchApplication.ListPrincipals s, global::System.Exception ex)
            {
                bool handled = false;
                s.ListPrincipals_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.ListPrincipals.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.ListPrincipals.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PrincipalsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Principals;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass, global::LightSwitchApplication.Principal>.Data _Principals;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass, global::LightSwitchApplication.Principal> Principals
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass, global::LightSwitchApplication.Principal>)base.GetItem(global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties.Principals);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass, global::LightSwitchApplication.Principal>.Entry
                    Principals = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass, global::LightSwitchApplication.Principal>.Entry(
                        "Principals",
                        global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties._Principals_Stub,
                        global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties._Principals_Validate,
                        global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties._Principals_CreateQuery,
                        global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties._Principals_SelectionChanged,
                        global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties._Principals_OnCollectionChanged,
                        global::LightSwitchApplication.ListPrincipals.DetailsClass.PropertySetProperties._Principals_OnLoaded);
                private static void _Principals_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ListPrincipals.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ListPrincipals, global::LightSwitchApplication.ListPrincipals.DetailsClass, global::LightSwitchApplication.Principal>.Data> c, global::LightSwitchApplication.ListPrincipals.DetailsClass d, object sf)
                {
                    c(d, ref d._Principals, sf);
                }
                private static void _Principals_Validate(global::LightSwitchApplication.ListPrincipals s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Principals_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Principals_CreateQuery(global::LightSwitchApplication.ListPrincipals.DetailsClass d, object[] args)
                {
                    return d.PrincipalsQuery();
                }
                private static void _Principals_SelectionChanged(global::LightSwitchApplication.ListPrincipals s)
                {
                    s.Principals_SelectionChanged();
                }
                private static void _Principals_OnCollectionChanged(global::LightSwitchApplication.ListPrincipals s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Principals_Changed(e);
                }
                private static void _Principals_OnLoaded(global::LightSwitchApplication.ListPrincipals s, bool succeeded)
                {
                    s.Principals_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
