

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Principal : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Principal entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Principal()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Principal(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Principal> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Principal.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Principal_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Principal_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Principal.DetailsClass.GetValue(this, global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Principal.DetailsClass.SetValue(this, global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PrincipalName
        {
            get
            {
                return global::LightSwitchApplication.Principal.DetailsClass.GetValue(this, global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties.PrincipalName);
            }
            set
            {
                global::LightSwitchApplication.Principal.DetailsClass.SetValue(this, global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties.PrincipalName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrincipalName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrincipalName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrincipalName_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Principal,
                global::LightSwitchApplication.Principal.DetailsClass,
                global::LightSwitchApplication.Principal.DetailsClass.IImplementation,
                global::LightSwitchApplication.Principal.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass>.Entry
                __PrincipalEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass>.Entry(
                    global::LightSwitchApplication.Principal.DetailsClass.__Principal_CreateNew,
                    global::LightSwitchApplication.Principal.DetailsClass.__Principal_Created,
                    global::LightSwitchApplication.Principal.DetailsClass.__Principal_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Principal __Principal_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Principal> es)
            {
                return new global::LightSwitchApplication.Principal(es);
            }
            private static void __Principal_Created(global::LightSwitchApplication.Principal e)
            {
                e.Principal_Created();
            }
            private static bool __Principal_AllowSaveWithErrors(global::LightSwitchApplication.Principal e)
            {
                bool result = false;
                e.Principal_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Principal.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, string> PrincipalName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties.PrincipalName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string PrincipalName { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Principal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, int>.Data> c, global::LightSwitchApplication.Principal.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Principal e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Principal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Principal.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Principal.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Principal e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, string>.Entry
                    PrincipalName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, string>.Entry(
                        "PrincipalName",
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._PrincipalName_Stub,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._PrincipalName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._PrincipalName_Validate,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._PrincipalName_GetImplementationValue,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._PrincipalName_SetImplementationValue,
                        global::LightSwitchApplication.Principal.DetailsClass.PropertySetProperties._PrincipalName_OnValueChanged);
                private static void _PrincipalName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Principal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, string>.Data> c, global::LightSwitchApplication.Principal.DetailsClass d, object sf)
                {
                    c(d, ref d._PrincipalName, sf);
                }
                private static bool _PrincipalName_ComputeIsReadOnly(global::LightSwitchApplication.Principal e)
                {
                    bool result = false;
                    e.PrincipalName_IsReadOnly(ref result);
                    return result;
                }
                private static void _PrincipalName_Validate(global::LightSwitchApplication.Principal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PrincipalName_Validate(r);
                }
                private static string _PrincipalName_GetImplementationValue(global::LightSwitchApplication.Principal.DetailsClass d)
                {
                    return d.ImplementationEntity.PrincipalName;
                }
                private static void _PrincipalName_SetImplementationValue(global::LightSwitchApplication.Principal.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PrincipalName = v;
                }
                private static void _PrincipalName_OnValueChanged(global::LightSwitchApplication.Principal e)
                {
                    e.PrincipalName_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Principal, global::LightSwitchApplication.Principal.DetailsClass, string>.Data _PrincipalName;
            
        }
    
        #endregion
    }
    
    #endregion
}
